---
configure_ssh: false
ssh_keys:
  - user: root
    key_files:
      - "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
      - "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"


run_yum_update: false

onboard_mde_agent: true
offboard_mde_agent: false

edr_enabled: true
edr_supported_rhel_versions:
  - 8
  - 9

mde_onboarding_file: "mdatp_onboard.json"
mde_onboarding_local_path: "files/onboarding/{{ mde_onboarding_file }}"
mde_onboarding_remote_path: "/etc/opt/microsoft/mdatp/{{ mde_onboarding_file }}"
mde_offboarding_file: "mdatp_offboard.json"
mde_offboarding_remote_path: "/etc/opt/microsoft/mdatp/{{ mde_offboarding_file }}"

mde_force_onboarding: false
mde_passive_mode: false
mde_force_offboarding: false

mde_tags:
  - key: "GROUP"
    value: "MDE-Management"
  - key: "ROLE"
    value: "RHEL-EDR"

mde_state: present | absent